### ISSUE TITLE
Unable to quickview files in quickviewed folders

### ISSUE THREAD

**Issue by xhm12345abcde** [adyanth/QuickLook.Plugin.FolderViewer#11]
Could you please tell me how to view the files in the folder I'm viewing? If I press space the interface will directly disappear.

**Comment by adyanth** [comment]
Are you trying to preview the file inside the preview? That won't work. You can expand the folders inside, but you cannot preview the files inside it.

**Comment by xhm12345abcde** [comment]
got it, thanks
