### ISSUE TITLE
Ready to be listed in the wiki?

### ISSUE THREAD

**Issue by rabelux** [adyanth/QuickLook.Plugin.FolderViewer#2]
Hi adyanth, thank you for building this plugin!
Would you mind if I add this plugin to the [wiki](https://github.com/QL-Win/QuickLook/wiki/Available-Plugins)?

And I wanted to let you know that mooflu added two more commits to his repo you might want to take a look at:
https://github.com/mooflu/QuickLook/commits/folder-preview

**Comment by adyanth** [comment]
Hey @rabelux 
I thought it was already listed! Please, feel free to add it.

Regarding the new commits, the search definitely looks good. Not too sure of the 5 level deep change, will try it out and see. Thanks for pointing that out!

**Comment by adyanth** [comment]
The search is for the Text viewer plugin that is already present in QuickLook core and not a part of this plugin.

**Comment by rabelux** [comment]
The search commit "Add search to TextViewer plugin" has already made it into Quicklook's official release. That's why I mentioned there are only 2 commits you might want to have look at:
https://github.com/mooflu/QuickLook/commit/5089fab2c3699e1658657d2d715ddf1f220ccd9c and https://github.com/mooflu/QuickLook/commit/27ab7d0cc9131f6ab60c87d50454093450e53ad3

**Comment by adyanth** [comment]
Missed the second one, got it, thanks!

**Comment by rabelux** [comment]
Done listing you in the wiki.
Could you maybe add a preview of your plugin to the readme? That way people know what to expect.

**Comment by adyanth** [comment]
Done!

**Comment by rabelux** [comment]
Awesome, thanks!
