### ISSUE TITLE
Is this program still being maintained, please?

### ISSUE THREAD

**Issue by fengyanfengyusuisuinian** [adyanth/QuickLook.Plugin.FolderViewer#20]
I see that this project has not been updated for a long time, has it been abandoned? Or maybe it's perfect enough and doesn't require frequent maintenance.

**Comment by adyanth** [comment]
I am not very familiar with C# and this was mostly a standalone publish, more details here: https://github.com/QL-Win/QuickLook/issues/575#issuecomment-753723340

And as it stands, it does not need any update to work as is. New features will be accepted on a case by case basis, but I am not working on this.
