### ISSUE TITLE
Version 1.2.1 (pre-release) doesn't have pre built binary

### ISSUE THREAD

**Issue by Inchworm333** [adyanth/QuickLook.Plugin.FolderViewer#3]
Would you mind releasing a compiled version of 1.2.1?

**Comment by adyanth** [comment]
Hey @Inchworm333 could you elaborate? This plugin does not depend on the QuickLook version. You can download and install the same. Does it not work for you?

**Comment by adyanth** [comment]
Ahh, my bad, you meant the version of this plugin. Will do!

**Comment by adyanth** [comment]
Done!
