### ISSUE TITLE
when I use this plugin, QuickLook may  die.

### ISSUE THREAD

**Issue by ylsds** [adyanth/QuickLook.Plugin.FolderViewer#5]
when the folder has many files, QuickLook will die. thank you .

**Comment by adyanth** [comment]
Hey @ylsds 
When you say QL dies, what do you mean? The whole application crashes? It might be good to report this on QL repo as well.

How many files do you have in the folder you tried, and what kind of files were they? I've seen video files take a long time, but not crash.

**Comment by ylsds** [comment]
Ql die means&nbsp; QL stop running and 1 minutes auto exit. in&nbsp; the folder have 120 files,&nbsp; music files and video files&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adyanth/QuickLook.Plugin.FolderViewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月27日(星期六) 晚上9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adyanth/QuickLook.Plugin.FolderViewer] when I use this plugin, QuickLook may  die. (Issue #5)





 
Hey @ylsds
 When you say QL dies, what do you mean? The whole application crashes? It might be good to report this on QL repo as well.
 
How many files do you have in the folder you tried, and what kind of files were they? I've seen video files take a long time, but not crash.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by adyanth** [comment]
If the whole app crashes, it is better to file a bug in the main repo here https://github.com/QL-Win/QuickLook. The application should not crash due to slow plugins.
