### ISSUE TITLE
请问怎么将这个插件添加到quick look里啊

### ISSUE THREAD

**Issue by wangchao277** [adyanth/QuickLook.Plugin.FolderViewer#9]
请问怎么将这个插件添加到quick look里啊

**Comment by adyanth** [comment]
Download the plugin from releases: https://github.com/adyanth/QuickLook.Plugin.FolderViewer/releases/
[Direct link to latest](https://github.com/adyanth/QuickLook.Plugin.FolderViewer/releases/download/1.3/QuickLook.Plugin.FolderViewer.qlplugin)

Instructions on how to install a plugin: https://github.com/QL-Win/QuickLook/wiki/Available-Plugins#how-to-install-or-upgrade-a-plugin
